### ISSUE TITLE
(Wiki) Client-Side XmlCommentsImporter

### ISSUE THREAD

**Issue by Deantwo** [lamronby/wcfextrasplus#1]
https://github.com/lamronby/wcfextrasplus/wiki/xmlcomments
```
<system.serviceModel>
  <client>
    <metadata>
      <wsdlImporters>
        <extension type="WCFExtras.Wsdl.Documentation.XmlCommentsImporter, WCFExtras" />
      </wsdlImporters>
    </metadata>
  </client>
</system.serviceModel>
```
This is incorrect and needs to be changed to `type="WCFExtrasPlus.Wsdl.Documentation.XmlCommentsImporter, WCFExtrasPlus"`.
Though I am still attempting to make this work, so there might be more that needs changing.

**Comment by Deantwo** [comment]
Likely the same issue on https://github.com/lamronby/wcfextrasplus/wiki/soapheaders.

**Comment by Deantwo** [comment]
[SampleWCFClient/app.config#L39](https://github.com/lamronby/wcfextrasplus/blob/master/Source/SampleWCFClient/app.config#L39) seems to have a better example. And I suppose it proves me right?

**Comment by lamronby** [comment]
Good catch! I've updated xmlcomments and soapheaders.
