### ISSUE TITLE
 Incorrect link to license

### ISSUE THREAD

**Issue by jnyrup** [lamronby/wcfextrasplus#11]
Since WCFExtrasPlus seems to use a standard MS-PL license, the user experience (at least mine) can be improved a bit by changing from `<PackageLicenseFile>` to `<PackageLicenseExpression>`.

Scenario: I use `Get-Package | Select-Object Id,LicenseUrl` to list all licenses in my projects and for WCFExtrasPlus it prints
```
WCFExtrasPlus                                              https://aka.ms/deprecateLicenseUrl
```

Or by viewing in NuGet Package Explorer
![image](https://user-images.githubusercontent.com/919634/111755563-894f9500-8899-11eb-9fa2-83fd506455ec.png)

As far as I understand the license displayed on show on https://www.nuget.org/packages/WCFExtrasPlus/
is generated upon ingestion of the nuget package where it stores the license file from `<PackageLicenseFile>` and generates a valid link to it.

If this is changed to 
```
<PackageLicenseExpression>MS-PL</PackageLicenseExpression>
```
the _nuget pack_ will include `https://licenses.nuget.org/MS-PL` in the generated .nuspec file.

Optionally use a combined approach, using `<PackageLicenseExpression>` and embedding the license file, see https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Newtonsoft.Json.csproj

**Comment by lamronby** [comment]
Fixed in package version 2.6.13.
