### ISSUE TITLE
[XmlSerializerFormat] annotation over interface can not create xml comment in WSDL file 

### ISSUE THREAD

**Issue by safayatborhan** [lamronby/wcfextrasplus#12]
Hi, 

I have put [XmlSerializerFormat] into interface. 

```
 [XmlComments]
    [ServiceContract]
    [XmlSerializerFormat]
    public interface IWsdlSample
    {
```

Now, all the "xs:documentation" inside "xs:annotation" are gone. Only "wsdl:documentation" are there.

![image](https://user-images.githubusercontent.com/13792572/116875082-2729d400-ac3c-11eb-8e2e-e0e40540a239.png)

**Comment by lamronby** [comment]
Why is this an issue?

**Comment by safayatborhan** [comment]
> Why is this an issue?

"xs:documentation" inside "xs:annotation" is missing if we use [XmlSerializerFormat]. Is there any workaround for it?

**Comment by lamronby** [comment]
I don't see any way to make this work. WCFExtrasPlus works by implementing a DataContractsSurrogate to add annotation content. When the [XmlSerializerFormat] is used, it overrides the default DataContractSerializer and uses XmlSerializer. With the XmlSerializer, the DataContractsSurrogate is not used. There's no equivalent surrogate for the XmlSerializer.

**Comment by safayatborhan** [comment]
> I don't see any way to make this work. WCFExtrasPlus works by implementing a DataContractsSurrogate to add annotation content. When the [XmlSerializerFormat] is used, it overrides the default DataContractSerializer and uses XmlSerializer. With the XmlSerializer, the DataContractsSurrogate is not used. There's no equivalent surrogate for the XmlSerializer.

I have found a workaround by comparing the generate xml file and adding specific annotation while exporting endpoint.

**Comment by safayatborhan** [comment]
> I don't see any way to make this work. WCFExtrasPlus works by implementing a DataContractsSurrogate to add annotation content. When the [XmlSerializerFormat] is used, it overrides the default DataContractSerializer and uses XmlSerializer. With the XmlSerializer, the DataContractsSurrogate is not used. There's no equivalent surrogate for the XmlSerializer.

 
@lamronby 
 If you agree, I want to contribute regarding annotation support for XmlSerializerFormat

**Comment by lamronby** [comment]
@safayatzisan Is the workaround you described something you implemented within the WCFExtrasPlus code? I would be interested in seeing the implementation.

**Comment by safayatborhan** [comment]
> @safayatzisan Is the workaround you described something you implemented within the WCFExtrasPlus code? I would be interested in seeing the implementation.

@lamronby sure. 

Here is the PR. Please check it out. 

https://github.com/lamronby/wcfextrasplus/pull/13
