### ISSUE TITLE
(Wiki) Installation Guide

### ISSUE THREAD

**Issue by Deantwo** [lamronby/wcfextrasplus#2]
Hello again, I am back to try and get this to work.
I am definitely missing a simple installation guide, but it could just be because this is my first time installing an WCF/WSDL extension.

After reading and doing what is described on [wiki/xmlcomments](https://github.com/lamronby/wcfextrasplus/wiki/xmlcomments) and seeing nothing happening, I have concluded that maybe I need do more than just that.

Going to the [wiki/wsdlextensions](https://github.com/lamronby/wcfextrasplus/wiki/wsdlextensions) page it seems like it might be a requirement, so I am attempting to do as described. However I am having trouble following the instructions.
I would very much love it if the examples on that page were given the full XML hierarchy.

For example, Change:
```
<behaviorExtensions>
  <add name="wsdlExtensions" type="WCFExtrasPlus.Wsdl.WsdlExtensionsConfig, WCFExtrasPlus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"/>
</behaviorExtensions>
```
To:
```
<system.serviceModel>
    <extensions>
        <behaviorExtensions>
            <add name="wsdlExtensions" type="WCFExtrasPlus.Wsdl.WsdlExtensionsConfig, WCFExtrasPlus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"/>
       </behaviorExtensions>
    </extensions>
</system.serviceModel>
```

Other than that, some clarification on what is actually required to make WCFExtrasPlus actually work would be very nice.

**Comment by Deantwo** [comment]
Best guide I have found is: http://www.andyfrench.info/2013/01/single-file-wsdl-generation-in-wcf.html
But even it has things that it doesn't explain.

For example this issue: https://stackoverflow.com/questions/5560331/wcfextras-the-element-bahavior-has-invalid-child-element-wsdlextensions
While I am still having issues after trying all this.

**Comment by askebv** [comment]
I was also having the issue that no comment was showing up, but it turns out all I forgot was to turn on XML comments for the project (Properties -> Build -> Xml Documentation File):
https://ewsoftware.github.io/XMLCommentsGuide/html/57C91630-95D6-4E3E-AF24-3415CC569AC8.htm

**Comment by rokx** [comment]
@Muskar This has to be written somewhere on the wiki page. I did everything, but this was unchecked.
One click and problem solved. Comment appear in wsdl.

**Comment by lamronby** [comment]
I added instructoins in the xmlcomments section of the wiki for enabling XML documentation. I also expanded the sample XML on the xmlcomments and wsdlextensions pages to include the full hierarchy.

**Comment by Deantwo** [comment]
Thanks @lamronby, I'll give it another try when I have time.
